spring:
    config:
      import: optional:file:.env[.properties]
    application:
      name: system

    devtools:
      restart:
        enabled: true
      livereload:
        enabled: true

    jpa:
      show-sql: true

    datasource:
      url: jdbc:${DATASOURCE_URL}
      username: ${DATASOURCE_USER}
      password: ${DATASOURCE_PASS}
      driver-class-name: org.postgresql.Driver

    flyway:
      enabled: true
      locations: classpath:db/postgresql
      baseline-on-migrate: true

